# Heritability Analysis

This note demonstrates the workflow for a typical heritability analysis in genetics, using a sample data set `cg10k` with **6,670** individuals and **630,860** SNPs. Person IDs and phenotype names are masked for privacy. Here `cg10k.bed`, `cg10k.bim`, and `cg10k.fam` is a set of Plink files in binary format. `cg10k_traits.txt` contains the phenotype data of 6,670 individuals.

In [1]:
;ls cg10k*.*

cg10k.bed
cg10k.bim
cg10k.fam
cg10k_traits.txt


## Read in binary SNP data

We will use the [`SnpArrays`](https://github.com/Hua-Zhou/SnpArrays.jl) package to read in binary SNP data and compute the empirical kinship matrix. Issue `Pkg.clone("git@github.com:Hua-Zhou/SnpArrays.jl.git")` within `Julia` to install the `SnpArrays` package.

In [2]:
#Pkg.clone("git@github.com:Hua-Zhou/SnpArrays.jl.git")
using SnpArrays
# read in genotype data from Plink binary file (~50 secs on my laptop)
@time copd = SnpArray("cg10k")

 50.915927 seconds (503.93 k allocations: 1.003 GB, 0.04% gc time)


6670x630860 SnpArrays.SnpArray{2}:
 (false,true)   (false,true)   (true,true)   …  (true,true)    (true,true) 
 (true,true)    (true,true)    (false,true)     (false,true)   (true,false)
 (true,true)    (true,true)    (false,true)     (true,true)    (true,true) 
 (true,true)    (true,true)    (true,true)      (false,true)   (true,true) 
 (true,true)    (true,true)    (true,true)      (true,true)    (false,true)
 (false,true)   (false,true)   (true,true)   …  (true,true)    (true,true) 
 (false,false)  (false,false)  (true,true)      (true,true)    (true,true) 
 (true,true)    (true,true)    (true,true)      (true,true)    (false,true)
 (true,true)    (true,true)    (false,true)     (true,true)    (true,true) 
 (true,true)    (true,true)    (true,true)      (false,true)   (true,true) 
 (true,true)    (true,true)    (false,true)  …  (true,true)    (true,true) 
 (false,true)   (false,true)   (true,true)      (true,true)    (false,true)
 (true,true)    (true,true)    (true,true)      (true

## Summary statistics of SNP data

In [3]:
people, snps = size(copd)

(6670,630860)

In [4]:
# summary statistics (~50 secs on my laptop)
@time maf, minor_allele, missings_by_snp, missings_by_person = summarize(copd)

 42.989971 seconds (42.38 k allocations: 11.660 MB)


([0.169916,0.17099,0.114026,0.268694,0.219265,0.23935,0.190612,0.20201,0.0271609,0.299714  …  0.207996,0.448012,0.295465,0.142654,0.170915,0.281428,0.0611354,0.0524738,0.13931,0.132413],Bool[true,true,true,true,true,true,true,true,true,true  …  true,true,true,true,true,true,true,true,true,true],[2,0,132,77,0,27,2,2,6,27  …  4,5,11,0,0,4,29,0,5,43],[364,1087,1846,1724,1540,248,215,273,273,224  …  1353,692,901,1039,685,304,223,1578,2059,1029])

In [5]:
# 5 number summary and average MAF (minor allele frequencies)
quantile(maf, [0.0 .25 .5 .75 1.0]), mean(maf)

(
1x5 Array{Float64,2}:
 0.00841726  0.124063  0.236953  0.364253  0.5,

0.24536516625042462)

In [58]:
using Plots
#pyplot()
gr()

histogram(maf, xlab = "Minor Allele Frequency (MAF)", label = "MAF")

[Plots.jl] Initializing backend: gr


INFO: Recompiling stale cache file /Users/hzhou3/.julia/lib/v0.4/GR.ji for module GR.


<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0 
 
 
 10000 
 
 
 20000 
 
 
 
 0.1 
 
 
 0.2 
 
 
 0.3 
 
 
 0.4 
 
 
 0.5 
 
 
 
 
 
 Minor Allele Frequency (MAF) 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 MAF

In [8]:
# total number of missing genotypes
sum(missings_by_snp)

5524131

In [59]:
# proportion of SNPs with maf > 0.05
countnz(maf .≥ 0.05) / length(maf)

0.9277193038075009

## Empirical kinship matrix

We estimate empirical kinship based on all SNPs by genetic relation matrix (GRM) and method of moment (MoM).

In [10]:
# GRM using all SNPs (~10 mins on my laptop)
srand(123)
@time Φgrm = grm(copd)

623.389668 seconds (4.21 G allocations: 64.486 GB, 1.14% gc time)


6670x6670 Array{Float64,2}:
  0.502916      0.00329978   -0.000116213  …  -6.46286e-5   -0.00281229 
  0.00329978    0.49892      -0.00201992       0.000909871   0.00345573 
 -0.000116213  -0.00201992    0.493632         0.000294565  -0.000349854
  0.000933977  -0.00320391   -0.0018611       -0.00241682   -0.00127078 
 -7.75429e-5   -0.0036075     0.00181442       0.00213976   -0.00158382 
  0.00200371    0.000577386   0.0025455    …   0.000943753  -1.82994e-6 
  0.000558503   0.00241421   -0.0018782        0.001217     -0.00123924 
 -0.000659495   0.00319987   -0.00101496       0.00353646   -0.00024093 
 -0.00102619   -0.00120448   -0.00055462       0.00175586    0.00181899 
 -0.00136838    0.00211996    0.000119128     -0.00147305   -0.00105239 
 -0.00206144    0.000148818  -0.000475177  …  -0.000265522  -0.00106123 
  0.000951016   0.00167042    0.00183545      -0.000703658  -0.00313334 
  0.000330442  -0.000904147   0.00301478       0.000754772  -0.00127413 
  ⋮                    

In [15]:
# MoM using all SNPs
srand(123)
@time Φmom = grm(copd; method = :MoM)

603.181891 seconds (4.21 G allocations: 64.478 GB, 1.02% gc time)


6670x6670 Array{Float64,2}:
  0.496512      0.000821702  -0.000437973  …   0.000582675  -0.00523526 
  0.000821702   0.499079     -0.00103315       0.00268612    0.00332432 
 -0.000437973  -0.00103315    0.500996         0.00358008    0.00200011 
  0.000310183  -0.00306489    0.00111332       0.000341257  -5.07485e-5 
  0.00150532   -0.000622024   0.00771765       0.00785389    0.00224631 
  0.00334344    0.00343905    0.00687627   …   0.00483258    0.0032072  
 -0.000397339   0.00201923    0.000723701      0.00338408   -0.000777392
 -0.00311508    0.0022965     0.00103205       0.00647709    0.000568333
 -0.00413573   -0.00235736    0.00138103       0.00345818    0.00161527 
 -0.00151838    0.0035251     0.00477761       0.00284388    0.000697408
 -0.00279718    0.000577894   0.00289407   …   0.00318329    9.2668e-5  
  0.00125673    0.00191167    0.00499034       0.00233236   -0.00157096 
 -0.000619634   0.000494234   0.00731608       0.00349881   -0.000124847
  ⋮                    

## Save results

We don't want to re-compute SnpArray and empirical kinship matrices again and again for heritibility analysis.

In [8]:
#using JLD
#@save "cg10k.jld"
#whos()

                 #163#wsession    280 bytes  JLD.JldWriteSession
                    ArrayViews    183 KB     Module
                          Base  33051 KB     Module
                         Blosc     37 KB     Module
                      Calculus    166 KB     Module
                    ColorTypes    314 KB     Module
                        Colors    748 KB     Module
                        Compat    306 KB     Module
                          Core   6620 KB     Module
                    DataArrays    915 KB     Module
                    DataFrames   1944 KB     Module
                 Distributions   1319 KB     Module
                        Docile    414 KB     Module
                   DualNumbers     58 KB     Module
                        FileIO    533 KB     Module
             FixedPointNumbers     33 KB     Module
               FixedSizeArrays    157 KB     Module
                            GR    414 KB     Module
                          GZip    637 KB     Module

To load workspace

In [1]:
using SnpArrays, JLD, DataFrames, VarianceComponentModels, Plots
gr()
@load "cg10k.jld"
whos()

                    ArrayViews    183 KB     Module
                          Base  29117 KB     Module
                         Blosc     37 KB     Module
                      Calculus    166 KB     Module
                    ColorTypes    248 KB     Module
                        Colors    576 KB     Module
                        Compat    247 KB     Module
                          Core   3399 KB     Module
                    DataArrays    865 KB     Module
                    DataFrames   1506 KB     Module
                 Distributions   1317 KB     Module
                        Docile    414 KB     Module
                   DualNumbers     57 KB     Module


                        FileIO    533 KB     Module
             FixedPointNumbers     32 KB     Module
               FixedSizeArrays    157 KB     Module
                          GZip    578 KB     Module
                          Grid    182 KB     Module
                          HDF5   2521 KB     Module
                        IJulia    402 KB     Module
                IPythonDisplay     33 KB     Module
                         Ipopt     26 KB     Module
              IterativeSolvers    485 KB     Module
                           JLD    699 KB     Module
                          JSON    194 KB     Module
                        KNITRO    273 KB     Module
                 KernelDensity     95 KB     Module
                          Main 2474124 KB     Module
                  MathProgBase    304 KB     Module
                      Measures     14 KB     Module
                       NaNMath    106 KB     Module
                        Nettle     57 KB     Module
           

## Phenotypes

Read in the phenotype data and compute descriptive statistics.

In [3]:
using DataFrames

cg10k_trait = readtable("cg10k_traits.txt"; 
    separator = ' ',
    names = [:FID; :IID; :Trait1; :Trait2; :Trait3; :Trait4; :Trait5; :Trait6; 
             :Trait7; :Trait8; :Trait9; :Trait10; :Trait11; :Trait12; :Trait13],  
    eltypes = [UTF8String; UTF8String; Float64; Float64; Float64; Float64; Float64; 
               Float64; Float64; Float64; Float64; Float64; Float64; Float64; Float64])

6670×15 DataFrames.DataFrame
│ Row  │ FID      │ IID      │ Trait1    │ Trait2    │ Trait3     │ Trait4     │
├──────┼──────────┼──────────┼───────────┼───────────┼────────────┼────────────┤
│ 1    │ "10002K" │ "10002K" │ -1.81573  │ -0.94615  │ 1.11363    │ -2.09867   │
│ 2    │ "10004O" │ "10004O" │ -1.2444   │ 0.10966   │ 0.467119   │ -1.62131   │
│ 3    │ "10005Q" │ "10005Q" │ 1.45567   │ 1.53867   │ 1.09403    │ 0.586655   │
│ 4    │ "10006S" │ "10006S" │ -0.768809 │ 0.513491  │ 0.244263   │ -1.3174    │
│ 5    │ "10009Y" │ "10009Y" │ -0.264415 │ -0.34824  │ -0.0239065 │ 0.00473916 │
│ 6    │ "10010J" │ "10010J" │ -1.37617  │ -1.47192  │ 0.29118    │ -0.803111  │
│ 7    │ "10011L" │ "10011L" │ 0.100942  │ -0.191616 │ -0.567421  │ 0.378571   │
│ 8    │ "10013P" │ "10013P" │ -0.319818 │ 1.35774   │ 0.81869    │ -1.15566   │
│ 9    │ "10014R" │ "10014R" │ -0.288334 │ 0.566083  │ 0.254958   │ -0.652578  │
│ 10   │ "10015T" │ "10015T" │ -1.1576   │ -0.781199 │ -0.595808  │ -1.00555   │
│ 11   │ "10017X" │ "10017X" │ 0.740569  │ 1.40874   │ 0.73469    │ 0.0208323  │
⋮
│ 6659 │ "25414M" │ "25414M" │ -0.131005 │ 0.425378  │ -1.09015   │ -0.42093   │
│ 6660 │ "25416Q" │ "25416Q" │ -0.52427  │ 1.04173   │ 1.13749    │ -1.27262   │
│ 6661 │ "25417S" │ "25417S" │ 1.32516   │ 0.905899  │ 0.84261    │ 0.869143   │
│ 6662 │ "25418U" │ "25418U" │ -1.44368  │ -2.55708  │ -0.868193  │ 0.390457   │
│ 6663 │ "25420H" │ "25420H" │ -1.8518   │ -1.25726  │ 1.81724    │ -2.17285   │
│ 6664 │ "25421J" │ "25421J" │ -0.810034 │ 0.0896703 │ 0.530939   │ -1.14212   │
│ 6665 │ "25422L" │ "25422L" │ -1.22395  │ -1.48953  │ -2.95847   │ -0.645307  │
│ 6666 │ "25425R" │ "25425R" │ -0.282847 │ -1.54129  │ -1.38819   │ 1.48327    │
│ 6667 │ "25426T" │ "25426T" │ 0.475008  │ 1.46697   │ 0.497403   │ -0.46861   │
│ 6668 │ "25428X" │ "25428X" │ -0.408154 │ -0.325323 │ 0.0850869  │ -0.182984  │
│ 6669 │ "25429Z" │ "25429Z" │ 0.886626  │ 0.487408  │ -0.0977307 │ 0.830857   │
│ 6670 │ "25430K" │ "25430K" │ -1.24394  │ 0.213697  │ 2.74965    │ -1.80285   │

│ Row  │ Trait5     │ Trait6     │ Trait7     │ Trait8    │ Trait9    │
├──────┼────────────┼────────────┼────────────┼───────────┼───────────┤
│ 1    │ 0.744417   │ 0.00139172 │ 0.934732   │ -1.22677  │ 1.11608   │
│ 2    │ 1.05668    │ 0.978947   │ 1.00015    │ 0.324874  │ 1.16232   │
│ 3    │ -0.327965  │ -0.303377  │ -0.0334355 │ -0.464463 │ -0.33194  │
│ 4    │ 1.19394    │ 1.17344    │ 1.08737    │ 0.536023  │ 0.802759  │
│ 5    │ 1.25619    │ 1.20389    │ 1.29801    │ 0.310114  │ 0.62616   │
│ 6    │ -0.26424   │ -0.260573  │ -0.165372  │ -0.219257 │ 1.04702   │
│ 7    │ -0.246656  │ -0.608811  │ 0.189081   │ -1.27078  │ -0.452476 │
│ 8    │ 0.634484   │ 0.291462   │ 0.933324   │ -0.741083 │ 0.647478  │
│ 9    │ 0.668922   │ 0.978309   │ 0.122863   │ 1.47909   │ 0.0672132 │
│ 10   │ 0.789829   │ 0.571058   │ 0.951304   │ -0.295963 │ 0.99042   │
│ 11   │ -0.337441  │ -0.458304  │ -0.142583  │ -0.580392 │ -0.684685 │
⋮
│ 6659 │ 0.310943   │ 0.735302   │ -0.0923875 │ 1.35506   │ 1.0652    │
│ 6660 │ -0.607382  │ -0.613654  │ -0.233233  │ -0.72178  │ 0.948663  │
│ 6661 │ -0.691461  │ -0.433578  │ -0.890664  │ 0.4462    │ -1.71787  │
│ 6662 │ -0.0331364 │ -2.6614    │ 0.750482   │ -5.62549  │ 0.86061   │
│ 6663 │ 0.948696   │ -0.351239  │ -0.16338   │ -0.376714 │ 0.781865  │
│ 6664 │ 1.26049    │ 1.30857    │ 1.00127    │ 0.876074  │ 1.37296   │
│ 6665 │ -2.67022   │ -1.74132   │ -4.1342    │ 2.52424   │ -1.4819   │
│ 6666 │ -1.23406   │ -1.10252   │ -0.717352  │ -0.905295 │ -1.07487  │
│ 6667 │ 0.496553   │ 0.195008   │ 0.661188   │ -0.544159 │ 1.54089   │
│ 6668 │ -0.46577   │ 0.251995   │ -0.915712  │ 1.62863   │ -2.2893   │
│ 6669 │ -0.168597  │ -0.586483  │ 0.256554   │ -1.32053  │ -1.10432  │
│ 6670 │ 1.11401    │ 1.16462    │ 1.1404     │ 0.451617  │ 1.40992   │

│ Row  │ Trait10     │ Trait11   │ Trait12    │ Trait13   │
├──────┼─────────────┼───────────┼────────────┼───────────┤
│ 1    │ -0.443628  

In [69]:
#describe(cg10k_trait)

In [62]:
Y = convert(Matrix{Float64}, cg10k_trait[:, 3:15])
histogram(Y, layout = 13)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0 
 
 
 200 
 
 
 400 
 
 
 600 
 
 
 
 - 
 
 
 2 
 
 
 0 
 
 
 2 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 y1 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0 
 
 
 200 
 
 
 400 
 
 
 600 
 
 
 
 - 
 
 
 2 
 
 
 0 
 
 
 2 
 
 
 4 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 y2 
 
 
 
 
 
 
 
 
 
 
 
 
 0 
 
 
 500 
 
 
 1000 
 
 
 
 0 
 
 
 5 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 y3 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0 
 
 
 200 
 
 
 400 
 
 
 600 
 
 
 800 
 
 
 
 - 
 
 
 2 
 
 
 0 
 
 
 2 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 y4 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0 
 
 
 200 
 
 
 400 
 
 
 
 - 
 
 
 4 
 
 
 - 
 
 
 2 
 
 
 0 
 
 
 2 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 y5 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0 
 
 
 200 
 
 
 400 
 
 
 
 - 
 
 
 2 
 
 
 0 
 
 
 2 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 y6 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0 
 
 
 200 
 
 
 400 
 
 
 600 
 
 
 
 - 
 
 
 4 
 
 
 - 
 
 
 2 
 
 
 0 
 
 
 2 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 y7 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0 
 
 
 500 
 
 
 1000 
 
 
 
 - 
 
 
 5 
 
 
 0 
 
 
 5 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 y8 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0 
 
 
 200 
 
 
 400 
 
 
 600 
 
 
 
 - 
 
 
 4 
 
 
 - 
 
 
 2 
 
 
 0 
 
 
 2 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 y9 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0 
 
 
 500 
 
 
 1000 
 
 
 
 0 
 
 
 5 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 y10 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0 
 
 
 200 
 
 
 400 
 
 
 600 
 
 
 
 - 
 
 
 2 
 
 
 0 
 
 
 2 
 
 
 4 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 y11 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0 
 
 
 1000 
 
 
 2000 
 
 
 
 - 
 
 
 5 
 
 
 0 
 
 
 5 
 
 
 10 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 y12 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0 
 
 
 1000 
 
 
 2000 
 
 
 3000 
 
 
 
 0 
 
 
 10 
 
 
 20

## Pre-processing data for heritability analysis

To prepare variance component model fitting, we form an instance of `VarianceComponentVariate`. The two variance components are $(2\Phi, I)$.

In [63]:
using VarianceComponentModels

# form data as VarianceComponentVariate
cg10kdata = VarianceComponentVariate(Y, (2Φgrm, eye(size(Y, 1))))
fieldnames(cg10kdata)

3-element Array{Symbol,1}:
 :Y
 :X
 :V

In [64]:
cg10kdata

VarianceComponentModels.VarianceComponentVariate{Float64,2,Array{Float64,2},Array{Float64,2},Array{Float64,2}}(6670x13 Array{Float64,2}:
 -1.81573   -0.94615     1.11363    …   0.824466  -1.02853     -0.394049 
 -1.2444     0.10966     0.467119       3.08264    1.09065      0.0256616
  1.45567    1.53867     1.09403       -1.10649   -1.42016     -0.687463 
 -0.768809   0.513491    0.244263       0.394175  -0.767366     0.0635386
 -0.264415  -0.34824    -0.0239065      0.549968   0.540688     0.179675 
 -1.37617   -1.47192     0.29118    …   0.947393   0.594015     0.245407 
  0.100942  -0.191616   -0.567421       0.332636   0.00269165   0.317117 
 -0.319818   1.35774     0.81869        0.220861   0.852512    -0.225905 
 -0.288334   0.566083    0.254958       0.167532   0.246916     0.539933 
 -1.1576    -0.781199   -0.595808       0.7331    -1.73468     -1.35278  
  0.740569   1.40874     0.73469    …  -0.712244  -0.313346    -0.345419 
 -0.675892   0.279893    0.267916      -0.809014 

Before fitting the variance component model, we pre-compute the eigen-decomposition of $2\Phi$, the rotated responses, and the constant part in log-likelihood, and store them as a `TwoVarCompVariateRotate` instance, which is re-used in various variane component estimation procedures.

In [7]:
@time cg10kdata_rotated = TwoVarCompVariateRotate(cg10kdata)
fieldnames(cg10kdata_rotated)

 54.869903 seconds (2.14 M allocations: 1.091 GB, 0.17% gc time)


4-element Array{Symbol,1}:
 :Yrot    
 :Xrot    
 :eigval  
 :logdetV2

## Heritability of single traits

Let's invoke Fisher scoring algorithm to fit variance component model for each single trait.

In [65]:
# heritability from single trait analysis
hST = zeros(13)
# standard errors of estimated heritability
hST_se = zeros(13)
# additive genetic effects
σ2a = zeros(13)
# enviromental effects
σ2e = zeros(13)

@time for trait in 1:13
    println(names(cg10k_trait)[trait + 2])
    # form data set for trait j
    traitj_data = TwoVarCompVariateRotate(cg10kdata_rotated.Yrot[:, trait], cg10kdata_rotated.Xrot, 
        cg10kdata_rotated.eigval, cg10kdata_rotated.logdetV2)
    # initialize model parameters
    traitj_model = VarianceComponentModel(traitj_data)
    # estimate variance components
    _, _, _, Σcov, _, _ = mle_fs!(traitj_model, traitj_data; solver=:Knitro, verbose=false)
    σ2a[trait] = traitj_model.Σ[1][1]
    σ2e[trait] = traitj_model.Σ[2][1]
    @show σ2a[trait], σ2e[trait]
    # estimate heritability from variance component estimates
    h, hse = heritability(traitj_model.Σ, Σcov)
    hST[trait] = h[1, 1]
    hST_se[trait] = hse[1, 1]
end

Trait1
(σ2a[trait],σ2e[trait]) = (0.26104124348442725,0.7356884322639051)
Trait2
(σ2a[trait],σ2e[trait]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(0.1887416044532389,0.8106898711546213)
Trait3
(σ2a[trait],σ2e[trait]) = (0.3185719312493481,0.6801458828228929)
Trait4
(σ2a[trait],σ2e[trait]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.
### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(0.2655690169564886,0.7303588329793687)
Trait5
(σ2a[trait],σ2e[trait]) = (0.2812332027554395,0.716798913627366)
Trait6
(σ2a[trait],σ2e[trait]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.
### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(0.282946114265676,0.7165629541234612)
Trait7
(σ2a[trait],σ2e[trait]) = (0.2154385871262379,0.7816210896082094)
Trait8
(σ2a[trait],σ2e[trait]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.
### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(0.19412650095405165,0.8055277516545418)
Trait9
(σ2a[trait],σ2e[trait]) = (0.2478956477632896,0.7504615498312688)
Trait10
(σ2a[trait],σ2e[trait]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.
### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(0.10007477232218753,0.899815065485574)
Trait11
(σ2a[trait],σ2e[trait]) = (0.16486781336071965,0.8338001946268672)
Trait12
(σ2a[trait],σ2e[trait]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.
### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(0.08298664768480632,0.9158035237004613)
Trait13


### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(σ2a[trait],σ2e[trait]) = (0.056842881348442224,0.9423649400242309)
  1.122919 seconds (23.28 M allocations: 379.506 MB, 22.47% gc time)


### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


In [66]:
# heritability and standard errors
[hST'; hST_se']

2x13 Array{Float64,2}:
 0.261041  0.188742  0.318572  0.265569  …  0.164868  0.0829866  0.0568429
 0.261041  0.188742  0.318572  0.265569     0.164868  0.0829866  0.0568429

## Pairwise traits

Following code snippet calculates joint heritability among all pairs of traits, a total of 78 bivariate variane component models.

In [2]:
# additive genetic effects (2x2 psd matrices) from bavariate trait analysis;
Σa = Array{Matrix{Float64}}(13, 13)
# environmental effects (2x2 psd matrices) from bavariate trait analysis;
Σe = Array{Matrix{Float64}}(13, 13)

@time for i in 1:13
    for j in (i+1):13
        println(names(cg10k_trait)[i + 2], names(cg10k_trait)[j + 2])
        # form data set for (trait1, trait2)
        traitij_data = TwoVarCompVariateRotate(cg10kdata_rotated.Yrot[:, [i;j]], cg10kdata_rotated.Xrot, 
            cg10kdata_rotated.eigval, cg10kdata_rotated.logdetV2)
        # initialize model parameters
        traitij_model = VarianceComponentModel(traitij_data)
        # estimate variance components
        mle_fs!(traitij_model, traitij_data; solver=:Knitro, verbose=false)
        Σa[i, j] = traitij_model.Σ[1]
        Σe[i, j] = traitij_model.Σ[2]
        @show Σa[i, j], Σe[i, j]
    end
end

Trait1Trait2
(Σa[i,j],Σe[i,j]) = (
[0.2601194348964541 0.17621582512277895
 0.17621582512277895 0.18737615485752512],

[0.7365894054973976 0.5838920950970753
 0.5838920950970753 0.8120331390127362])
Trait1Trait3
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.2615639935926094 -0.013126817780793214
 -0.013126817780793214 0.31905662257097117],

[0.735180211126028 -0.12112674792808123
 -0.12112674792808123 0.6796789899029853])
Trait1Trait4
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.26087960318141157 0.22261440535048016
 0.22261440535048016 0.2655808327657969],

[0.735845998143173 0.5994353346472087
 0.5994353346472087 0.7303474474454928])
Trait1Trait5
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.2607830377228154 -0.14701178350993233
 -0.14701178350993233 0.2818772454723132],

[0.7359373011101096 -0.2545838902422242
 -0.2545838902422242 0.7161761241953599])
Trait1Trait6
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.26070703554549013 -0.12935642543187742
 -0.12935642543187742 0.283188384872443],

[0.736012880695363 -0.23136128305018647
 -0.23136128305018647 0.7163294323340943])
Trait1Trait7
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.2603075007680344 -0.14025753695938906
 -0.14025753695938906 0.2150805562724711],

[0.7364055998579867 -0.1978054756062872
 -0.1978054756062872 0.7819851899006235])
Trait1Trait8
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.2610345999388007 -0.03352962807665258
 -0.03352962807665258 0.19414307318688134],

[0.7356949686801932 -0.12627246291042643
 -0.12627246291042643 0.8055115370349347])
Trait1Trait9
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.2630163172044493 -0.20486492581503218
 -0.20486492581503218 0.24679565383676802],

[0.7337944611630909 -0.30745003491312045
 -0.30745003491312045 0.7515442199108797])
Trait1Trait10
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.2608980791359058 -0.09981756194808718
 -0.09981756194808718 0.09702328559206955],

[0.7358279769094033 -0.3036087587979049
 -0.3036087587979049 0.902853465035614])
Trait1Trait11
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.26073970768658605 -0.13898341547608112
 -0.13898341547608112 0.16306263191095094],

[0.7359820027658017 -0.3591745314581508
 -0.3591745314581508 0.8355950431372585])
Trait1Trait12
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.26306859877320704 -0.14553556873504764
 -0.14553556873504764 0.0805136112083407],

[0.7337809619709013 -0.041697484631477294
 -0.041697484631477294 0.9183594161731263])
Trait1Trait13
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.26234367617866655 -0.10889551673493053
 -0.10889551673493053 0.0512940408244084],

[0.7344496460809519 -0.1139955836271247
 -0.1139955836271247 0.9479423983042337])
Trait2Trait3
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.18901532617422148 0.14615742883833768
 0.14615742883833768 0.32052865892659477],

[0.8104184412088634 0.0974992388634659
 0.0974992388634659 0.6782713240607734])
Trait2Trait4
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.18839515002390425 0.075214646726405
 0.075214646726405 0.26555848044260477],

[0.8110301027212233 0.2204948319881865
 0.2204948319881865 0.7303691342305628])
Trait2Trait5
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.18871644008719582 -0.011314016957150876
 -0.011314016957150876 0.28124653355732165],

[0.8107145247266807 -0.03701047035093756
 -0.03701047035093756 0.7167859986411548])
Trait2Trait6
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.1887737599685005 -0.0031066020966231504
 -0.0031066020966231504 0.2830125133352222],

[0.810658365650435 -0.021182657151034387
 -0.021182657151034387 0.7164985873463716])
Trait2Trait7
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.18835222586429093 -0.029957926228231294
 -0.029957926228231294 0.2151885425846749],

[0.8110719441199765 -0.0013693877011832908
 -0.0013693877011832908 0.7818678817134839])
Trait2Trait8
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.18926168901710827 0.03314229378949371
 0.03314229378949371 0.19466629554771392],

[0.8101822287272349 -0.03260026724579226
 -0.03260026724579226 0.8050045055525228])
Trait2Trait9
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.18728489590977687 -0.0854145852787251
 -0.0854145852787251 0.2467188036313337],

[0.8121330453225064 -0.08087908635486975
 -0.08087908635486975 0.7516171284784703])
Trait2Trait10
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.18896456315711202 -0.1253188038929318
 -0.1253188038929318 0.10012137258695945],

[0.8104983817334861 -0.2710710225593239
 -0.2710710225593239 0.8998490672650076])
Trait2Trait11
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.18776203849933698 -0.11847922057924713
 -0.11847922057924713 0.16627346454447847],

[0.8116527825640268 -0.29554897771811217
 -0.29554897771811217 0.832437229193212])
Trait2Trait12
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.18819063539059416 -0.09053833092058956
 -0.09053833092058956 0.08226341443411922],

[0.8112716595870646 0.04542203323872533
 0.04542203323872533 0.9165863316200414])
Trait2Trait13
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.18826030592279702 -0.0707041233179004
 -0.0707041233179004 0.05472389511335382],

[0.8112166103421603 0.07379770021108677
 0.07379770021108677 0.9445208387947039])
Trait3Trait4
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.3185203954068529 -0.1543389372267733
 -0.1543389372267733 0.26475409906441244],

[0.6801958865778387 -0.30343995140607727
 -0.30343995140607727 0.7311518515321918])
Trait3Trait5
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.31896997788766146 0.18435446667874872
 0.18435446667874872 0.2825001772566387],

[0.6797599597754401 0.33641052403302724
 0.33641052403302724 0.7155665412131724])
Trait3Trait6
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.31956636444368736 0.1666398876620828
 0.1666398876620828 0.28503131825251854],

[0.6791832508144467 0.29769765901208894
 0.29769765901208894 0.7145358499800598])
Trait3Trait7
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.3185755051604698 0.1668521600513683
 0.1668521600513683 0.21523224228199267],

[0.6801424314729608 0.34713884153376445
 0.34713884153376445 0.7818231309752512])
Trait3Trait8
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.32049923488929805 0.05753194040335204
 0.05753194040335204 0.1972448986306561],

[0.6782830497321767 0.04425974059200959
 0.04425974059200959 0.8024737831816315])
Trait3Trait9
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.3187191200344409 0.13729240544495633
 0.13729240544495633 0.24697586634589072],

[0.6800039145395823 0.26710543682695337
 0.26710543682695337 0.7513573840619613])
Trait3Trait10
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.31891521326636224 -0.0786338235412703
 -0.0786338235412703 0.10110317208096006],

[0.6798145588403067 -0.14078871560243073
 -0.14078871560243073 0.89879827116815])
Trait3Trait11
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.31782233049896236 -0.01798395920706984
 -0.01798395920706984 0.16474292122370326],

[0.6808712744431717 -0.11416573006759104
 -0.11416573006759104 0.8339228728455692])
Trait3Trait12
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.32088834022931845 0.08452483763216569
 0.08452483763216569 0.08698675056813215],

[0.6779139476759123 0.034013270970585624
 0.034013270970585624 0.9118411340081362])
Trait3Trait13
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.3230087934353965 0.11068106846891633
 0.11068106846891633 0.06117390037500833],

[0.6759011384327414 -0.007296624944618465
 -0.007296624944618465 0.938072254032927])
Trait4Trait5
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.2656669903879563 -0.21584756083662576
 -0.21584756083662576 0.28291866204393934],

[0.7302544029985172 -0.37667528249282817
 -0.37667528249282817 0.7151643526746791])
Trait4Trait6
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.26614305302289665 -0.20063378201231885
 -0.20063378201231885 0.2844419499990313],

[0.7297943215223454 -0.3468040722456415
 -0.3468040722456415 0.7151119490020976])
Trait4Trait7
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.2644898029547169 -0.18275157347879745
 -0.18275157347879745 0.21411680027044472],

[0.7314145610040846 -0.3261719947443792
 -0.3261719947443792 0.7829351279637835])
Trait4Trait8
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.26669395425707937 -0.09763540115745578
 -0.09763540115745578 0.19612608725235053],

[0.7292655955471785 -0.15036048119326256
 -0.15036048119326256 0.8035709853503825])
Trait4Trait9
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.2700365202924365 -0.22740698735288148
 -0.22740698735288148 0.24804582222346663],

[0.7260245140697723 -0.4156014351026267
 -0.4156014351026267 0.7502976666853451])
Trait4Trait10
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.26554294185785626 -0.03381072172397164
 -0.03381072172397164 0.09960982641894972],

[0.7303952879390379 -0.2277248992434568
 -0.2277248992434568 0.9002752447208877])
Trait4Trait11
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.26562760221214865 -0.09674003333472606
 -0.09674003333472606 0.1632740908958326],

[0.7303019079346017 -0.27261119472933504
 -0.27261119472933504 0.8353713024842476])
Trait4Trait12
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.26816369746682395 -0.1416126097104043
 -0.1416126097104043 0.08039678154077977],

[0.7278825924053214 -0.08284654908047545
 -0.08284654908047545 0.9184455528804105])
Trait4Trait13
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.2661712321570916 -0.09807308746707044
 -0.09807308746707044 0.054010192765202136],

[0.729774933173427 -0.2250595064473025
 -0.2250595064473025 0.9452044734624567])
Trait5Trait6
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.2815916532977691 0.2808983722482269
 0.2808983722482269 0.2822980508780423],

[0.7164553605785596 0.660367649411791
 0.660367649411791 0.7171950640738056])
Trait5Trait7
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.2808143739118041 0.23209986892753054
 0.23209986892753054 0.2116620427725187],

[0.7172180316987536 0.6743038171521138
 0.6743038171521138 0.7853426270875485])
Trait5Trait8
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.28134012178839235 0.16394787430303073
 0.16394787430303073 0.19270331045505631],

[0.716700910896753 0.221032108312193
 0.221032108312193 0.8069220955922851])
Trait5Trait9
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.28387780254607986 0.24453172575281926
 0.24453172575281926 0.24129303742473318],

[0.7142441394826087 0.5084169866069836
 0.5084169866069836 0.7568942337597353])
Trait5Trait10
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.28181301792525476 -0.04621142758701529
 -0.04621142758701529 0.1014806940553005],

[0.7162383324275362 -0.057210985162868676
 -0.057210985162868676 0.8984242853785952])
Trait5Trait11
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.28042354202802805 0.020249545536773814
 0.020249545536773814 0.16400332032202208],

[0.7175856258107098 -0.03524364665178476
 -0.03524364665178476 0.8346493307578223])
Trait5Trait12
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.2814270698034085 0.06161306628510395
 0.06161306628510395 0.08271662820266365],

[0.7166145561475198 0.052928643598281554
 0.052928643598281554 0.9160739284409782])
Trait5Trait13
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.2822915337284387 0.0704220517748874
 0.0704220517748874 0.056946310362329486],

[0.715782311420482 0.05283744422795921
 0.05283744422795921 0.9422684288663419])
Trait6Trait7
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.28296107606784127 0.22065632109231745
 0.22065632109231745 0.21385609771748407],

[0.716548671939106 0.5810829179757592
 0.5810829179757592 0.7831785715566235])
Trait6Trait8
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.2829606227483756 0.18407962650938378
 0.18407962650938378 0.1923790225235219],

[0.7165491133313817 0.4365973886384383
 0.4365973886384383 0.8072460050703656])
Trait6Trait9
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.28497844067328854 0.23443573779952176
 0.23443573779952176 0.24320710815424332],

[0.714600530478186 0.4768263386027498
 0.4768263386027498 0.7550279956930294])
Trait6Trait10
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.28365475694669917 -0.04354848113181606
 -0.04354848113181606 0.10202532170770666],

[0.715876865056982 -0.05916812475707061
 -0.05916812475707061 0.8978859539144105])
Trait6Trait11
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.2815224137120917 0.02799919843009905
 0.02799919843009905 0.1634299131702846],

[0.7179464769366606 -0.05241060597829893
 -0.05241060597829893 0.835213087524897])
Trait6Trait12
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.2831143444397669 0.05713989948521157
 0.05713989948521157 0.08267893145261165],

[0.7164030333189834 0.04791987044143614
 0.04791987044143614 0.916112029667119])
Trait6Trait13
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.28381996720737707 0.061121203355362315
 0.061121203355362315 0.057081690097934075],

[0.7157217792291151 0.053269833941786304
 0.053269833941786304 0.9421333541525764])
Trait7Trait8
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.21385686369999418 0.08845552025294963
 0.08845552025294963 0.1923730551778735],

[0.7831777633665448 -0.05683305765917501
 -0.05683305765917501 0.8072518673825895])
Trait7Trait9
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.21875569607348663 0.21704186386681662
 0.21704186386681662 0.24414386509618974],

[0.7784327750019111 0.4629009678935976
 0.4629009678935976 0.7541229287369298])
Trait7Trait10
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.2162729625132682 -0.042114572668696955
 -0.042114572668696955 0.10209048405207677],

[0.7808073890597902 -0.08590745174176291
 -0.08590745174176291 0.8978220135332078])
Trait7Trait11
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.21406877669079483 0.020696687056588017
 0.020696687056588017 0.16347380958931745],

[0.7829608190098544 -0.04814800953514762
 -0.04814800953514762 0.8351704865898087])
Trait7Trait12
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.21493232528947345 0.07578743207893562
 0.07578743207893562 0.08087309162289993],

[0.7821316766196906 0.03469555539642553
 0.03469555539642553 0.9179149810076269])
Trait7Trait13
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.21595864350873106 0.07493726631260939
 0.07493726631260939 0.05459341224418834],

[0.781138733381237 0.03890579486821109
 0.03890579486821109 0.9446215728546085])
Trait8Trait9
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.194554999403544 0.11281615599311134
 0.11281615599311134 0.24724415203577277],

[0.8051240569806172 0.1847784334012313
 0.1847784334012313 0.7510982276993133])
Trait8Trait10
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.19444100264330594 -0.015634153693736903
 -0.015634153693736903 0.10042647895831681],

[0.8052215712093918 0.011982590593664076
 0.011982590593664076 0.8994678452817971])
Trait8Trait11
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.1938531643865603 0.022532462988616442
 0.022532462988616442 0.16466854386875113],

[0.8057962945247231 -0.027274735067614964
 -0.027274735067614964 0.8339969682622992])
Trait8Trait12
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.1939512185569772 -0.0028760120513720627
 -0.0028760120513720627 0.08285727490554781],

[0.8056997963051779 0.03361278649605695
 0.03361278649605695 0.9159318671452308])
Trait8Trait13
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.19397976164756958 0.004078666732893958
 0.004078666732893958 0.05690712355019478],

[0.8056716011519816 0.037881706240189786
 0.037881706240189786 0.94230107732751])
Trait9Trait10
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.2472938323877671 -0.0023083630653646598
 -0.0023083630653646598 0.09982638796927838],

[0.7510505981273005 0.07407294272324245
 0.07407294272324245 0.9000613326287148])
Trait9Trait11
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.24782344374862597 0.031823503110037926
 0.031823503110037926 0.16489046415584996],

[0.7505321390503218 0.15228537745550527
 0.15228537745550527 0.8337779553054786])
Trait9Trait12
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.2503346952238479 0.08457136159702854
 0.08457136159702854 0.08875872360925961],

[0.7480909648615884 0.10775632068469104
 0.10775632068469104 0.9101080911475219])
Trait9Trait13
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.24944189424722088 0.09348451307850937
 0.09348451307850937 0.057932015412811455],

[0.7489745639634512 0.09821909743478888
 0.09821909743478888 0.9413348850801141])
Trait10Trait11
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.0931396709621361 0.10003371554811519
 0.10003371554811519 0.16495492792205232],

[0.9067034420998111 0.4744266619079698
 0.4744266619079698 0.8337151519152737])
Trait10Trait12
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.09672471733423346 0.056404344844088135
 0.056404344844088135 0.07945282818254669],

[0.9031497832360159 0.08532319470593383
 0.08532319470593383 0.919334342330677])
Trait10Trait13
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.10098492198488679 -0.027991586739406292
 -0.027991586739406292 0.05783694167621941],

[0.8989368213245167 0.1660507727532608
 0.1660507727532608 0.9413901793900357])
Trait11Trait12
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.16384057748165715 0.05703177998313149
 0.05703177998313149 0.07921436821499388],

[0.8348140971994676 0.1455965107998053
 0.1455965107998053 0.9195521320694227])
Trait11Trait13
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.16488293344606353 -0.0015841370683006104
 -0.0015841370683006104 0.05749684397777908],

[0.833797948821629 0.20061222756374675
 0.20061222756374675 0.9417152318762243])
Trait12Trait13
(Σa[i,j],Σe[i,j]) = 

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


(
[0.08459517874933027 0.06850620327544214
 0.06850620327544214 0.0554771581601963],

[0.9142134905816461 0.5731514383815555
 0.5731514383815555 0.943733788071119])
 86.423563 seconds (1.92 G allocations: 30.350 GB, 4.91% gc time)


### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


## 5-trait analysis

Researchers want to jointly analyze traits 5-9. Our strategy is to try both Fisher scoring and MM algorithm with different starting point, and choose the best local optimum.

In [45]:
traitidx = 5:9
# form data set
trait59_data = TwoVarCompVariateRotate(cg10kdata_rotated.Yrot[:, traitidx], cg10kdata_rotated.Xrot, 
    cg10kdata_rotated.eigval, cg10kdata_rotated.logdetV2)
# initialize model parameters
trait59_model = VarianceComponentModel(trait59_data)
# estimate variance components
@time mle_fs!(trait59_model, trait59_data; solver=:Knitro, verbose=true)
trait59_model


Knitro 10.1.0 STUDENT LICENSE (problem size limit = 300)

            Student License
       (NOT FOR COMMERCIAL USE)
         Artelys Knitro 10.1.0

Knitro presolve eliminated 0 variables and 0 constraints.

algorithm:            1
The problem is identified as bound constrained only.
Knitro changing bar_initpt from AUTO to 3.
Knitro changing bar_murule from AUTO to 4.
Knitro changing bar_penaltycons from AUTO to 1.
Knitro changing bar_penaltyrule from AUTO to 2.
Knitro changing bar_switchrule from AUTO to 1.
Knitro changing linsolver from AUTO to 2.

Problem Characteristics                    ( Presolved)
-----------------------
Objective goal:  Maximize
Number of variables:                    30 (        30)
    bounded below:                      10 (        10)
    bounded above:                       0 (         0)
    bounded below and above:             0 (         0)
    fixed:                               0 (         0)
    free:                               20 (        20)

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


VarianceComponentModels.VarianceComponentModel{Float64,2,Array{Float64,2},Array{Float64,2}}(0x5 Array{Float64,2},(
5x5 Array{Float64,2}:
 0.293285  0.286273  0.246039   0.156834   0.265501
 0.286273  0.287347  0.224065   0.187732   0.254287
 0.246039  0.224065  0.252785   0.0431791  0.191771
 0.156834  0.187732  0.0431791  0.259103   0.174374
 0.265501  0.254287  0.191771   0.174374   0.377391,

5x5 Array{Float64,2}:
 0.705656  0.65533    0.661038    0.22789    0.497238
 0.65533   0.712524   0.57635     0.435353   0.462432
 0.661038  0.57635    0.74447    -0.0140503  0.493485
 0.22789   0.435353  -0.0140503   0.747925   0.125282
 0.497238  0.462432   0.493485    0.125282   0.74239 ))

We see Fisher scoring is having trouble finding the optimum. Let's try the MM algorithm, starting from the Fisher scoring answer.

In [46]:
# trait59_model contains the fitted model by Fisher scoring now
@time mle_mm!(trait59_model, trait59_data; verbose=true)
trait59_model


     MM Algorithm
  Iter      Objective  
--------  -------------
       0   8.705871e+03
       1   8.757960e+03
       2   8.773751e+03
       3   8.778653e+03
       4   8.780308e+03
       5   8.780982e+03
       6   8.781350e+03
       7   8.781619e+03
       8   8.781851e+03
       9   8.782068e+03
      10   8.782277e+03
      20   8.784119e+03
      30   8.785626e+03
      40   8.786891e+03
      50   8.787989e+03
      60   8.788997e+03
      70   8.789999e+03
      80   8.791101e+03
      90   8.792448e+03
     100   8.794239e+03
     110   8.796745e+03
     120   8.800327e+03
     130   8.805422e+03
     140   8.812485e+03
     150   8.821859e+03
     160   8.833572e+03
     170   8.847171e+03
     180   8.861722e+03
     190   8.876067e+03
     200   8.889196e+03
     210   8.900503e+03
     220   8.909810e+03
     230   8.917248e+03
     240   8.923090e+03
     250   8.927647e+03
     260   8.931201e+03
     270   8.933986e+03
     280   8.936185e+03
     290   8.937938e+

VarianceComponentModels.VarianceComponentModel{Float64,2,Array{Float64,2},Array{Float64,2}}(0x5 Array{Float64,2},(
5x5 Array{Float64,2}:
 0.232505   0.207127   0.213454   0.0663597  0.218199 
 0.207127   0.185167   0.188206   0.0627829  0.190923 
 0.213454   0.188206   0.205745   0.0447439  0.20381  
 0.0663597  0.0627829  0.0447439  0.0464538  0.0517928
 0.218199   0.190923   0.20381    0.0517928  0.235715 ,

5x5 Array{Float64,2}:
 0.764114  0.732092   0.692173    0.316228   0.534003
 0.732092  0.811758   0.612219    0.555289   0.519043
 0.692173  0.612219   0.79091    -0.0148224  0.475712
 0.316228  0.555289  -0.0148224   0.951042   0.244044
 0.534003  0.519043   0.475712    0.244044   0.762242))

Do another run of MM algorithm from default starting point. It leads to a better local optimum. Follow up anlaysis should use this result.

In [47]:
# default starting point
trait59_model = VarianceComponentModel(trait59_data)
@time _, _, _, Σcov, = mle_mm!(trait59_model, trait59_data; verbose=true)
trait59_model


     MM Algorithm
  Iter      Objective  
--------  -------------
       0  -5.042149e+04
       1  -1.699687e+04
       2  -1.543968e+03
       3   5.143609e+03
       4   7.669359e+03
       5   8.489390e+03
       6   8.728893e+03
       7   8.796019e+03
       8   8.815880e+03
       9   8.823279e+03
      10   8.827419e+03
      20   8.854389e+03
      30   8.874943e+03
      40   8.890795e+03
      50   8.903062e+03
      60   8.912619e+03
      70   8.920130e+03
      80   8.926088e+03
      90   8.930861e+03
     100   8.934721e+03
     110   8.937872e+03
     120   8.940467e+03
     130   8.942622e+03
     140   8.944425e+03
     150   8.945946e+03
     160   8.947237e+03
     170   8.948339e+03
     180   8.949287e+03
     190   8.950106e+03
     200   8.950818e+03
     210   8.951439e+03
     220   8.951983e+03
     230   8.952462e+03
     240   8.952886e+03
     250   8.953262e+03
     260   8.953597e+03
     270   8.953896e+03
     280   8.954164e+03
     290   8.954404e+

VarianceComponentModels.VarianceComponentModel{Float64,2,Array{Float64,2},Array{Float64,2}}(0x5 Array{Float64,2},(
5x5 Array{Float64,2}:
 0.28408   0.282346  0.235651   0.163231   0.243528
 0.282346  0.287797  0.222888   0.189209   0.231229
 0.235651  0.222888  0.215833   0.0895747  0.212778
 0.163231  0.189209  0.0895747  0.199473   0.107541
 0.243528  0.231229  0.212778   0.107541   0.246379,

5x5 Array{Float64,2}:
 0.714039  0.65898    0.67085     0.221737   0.509435
 0.65898   0.711746   0.578905    0.431453   0.480001
 0.67085   0.578905   0.781276   -0.0579601  0.467102
 0.221737  0.431453  -0.0579601   0.800138   0.189943
 0.509435  0.480001   0.467102    0.189943   0.751844))

Heritability from 5-variate estimate and their standard errors.

In [49]:
h, hse = heritability(trait59_model.Σ, Σcov)
[h'; hse']

2x5 Array{Float64,2}:
 0.284615   0.287928   0.216459  0.199551   0.246817 
 0.0774592  0.0770454  0.08369   0.0850318  0.0809451

## 13-trait analysis

Researchers would like to jointly analyze all 13 traits. Fisher scoring algorithm (with KNITRO backend) again has trouble finding the optimum, ending with `OptError` of 2.11e+03. 

In [51]:
# initialize model parameters
alltrait_model = VarianceComponentModel(cg10kdata_rotated)
# estimate variance components
@time mle_fs!(alltrait_model, cg10kdata_rotated; solver=:Knitro, verbose=true)
alltrait_model


Knitro 10.1.0 STUDENT LICENSE (problem size limit = 300)

            Student License
       (NOT FOR COMMERCIAL USE)
         Artelys Knitro 10.1.0

Knitro presolve eliminated 0 variables and 0 constraints.

algorithm:            1
The problem is identified as bound constrained only.
Knitro changing bar_initpt from AUTO to 3.
Knitro changing bar_murule from AUTO to 4.
Knitro changing bar_penaltycons from AUTO to 1.
Knitro changing bar_penaltyrule from AUTO to 2.
Knitro changing bar_switchrule from AUTO to 1.
Knitro changing linsolver from AUTO to 2.

Problem Characteristics                    ( Presolved)
-----------------------
Objective goal:  Maximize
Number of variables:                   182 (       182)
    bounded below:                      26 (        26)
    bounded above:                       0 (         0)
    bounded below and above:             0 (         0)
    fixed:                               0 (         0)
    free:                              156 (       156)

### Could not find a valid license.
    Your machine ID is 1f-aa-f6-5b-46.
    Please contact licensing@artelys.com or your local distributor to obtain a license.
    If you already have a license, please execute `get_machine_ID -v` and send the output to support.


VarianceComponentModels.VarianceComponentModel{Float64,2,Array{Float64,2},Array{Float64,2}}(0x13 Array{Float64,2},(
13x13 Array{Float64,2}:
  0.314349    0.132106     -0.0354149  …  -0.136163    -0.1057    
  0.132106    0.139838      0.14053       -0.01739     -0.0045432 
 -0.0354149   0.14053       0.356969       0.0760162    0.092202  
  0.3435      0.0544454    -0.205904      -0.179036    -0.150632  
 -0.129431    0.0162413     0.18923        0.0740475    0.0695918 
 -0.113559    0.00982848    0.160951   …   0.0670134    0.0576479 
 -0.103943    0.0127981     0.167589       0.0754349    0.0715262 
 -0.0549323   0.000389919   0.0502953      0.00850429   0.00325788
 -0.205308   -0.0387772     0.154017       0.085873     0.0790097 
 -0.147019   -0.085665     -0.064819       0.127711     0.0730854 
 -0.155357   -0.0717892    -0.0087627  …   0.0946257    0.0511083 
 -0.136163   -0.01739       0.0760162      0.357154     0.236549  
 -0.1057     -0.0045432     0.092202       0.236549     

Re-run using MM algorithm, which locates a better mode. Follow up anlaysis should use this result.

In [53]:
# initialize model parameters
alltrait_model = VarianceComponentModel(cg10kdata_rotated)
# estimate variance components
@time _, _, _, Σcov, = mle_mm!(alltrait_model, cg10kdata_rotated; verbose=true)
alltrait_model


     MM Algorithm
  Iter      Objective  
--------  -------------
       0  -1.311337e+05
       1  -8.002195e+04
       2  -5.807051e+04
       3  -4.926234e+04
       4  -4.611182e+04
       5  -4.511727e+04
       6  -4.482798e+04
       7  -4.474410e+04
       8  -4.471610e+04
       9  -4.470285e+04
      10  -4.469355e+04
      20  -4.462331e+04
      30  -4.456960e+04
      40  -4.452834e+04
      50  -4.449652e+04
      60  -4.447178e+04
      70  -4.445237e+04
      80  -4.443699e+04
      90  -4.442467e+04
     100  -4.441470e+04
     110  -4.440656e+04
     120  -4.439985e+04
     130  -4.439427e+04
     140  -4.438959e+04
     150  -4.438564e+04
     160  -4.438229e+04
     170  -4.437941e+04
     180  -4.437694e+04
     190  -4.437480e+04
     200  -4.437294e+04
     210  -4.437131e+04
     220  -4.436989e+04
     230  -4.436863e+04
     240  -4.436751e+04
     250  -4.436652e+04
     260  -4.436564e+04
     270  -4.436485e+04
     280  -4.436414e+04
     290  -4.436351e+

VarianceComponentModels.VarianceComponentModel{Float64,2,Array{Float64,2},Array{Float64,2}}(0x13 Array{Float64,2},(
13x13 Array{Float64,2}:
  0.273498    0.192141    -0.0207392   0.231615   …  -0.128643   -0.098307  
  0.192141    0.219573     0.134389    0.0800317     -0.0687355  -0.0433724 
 -0.0207392   0.134389     0.329149   -0.158086       0.0717258   0.097381  
  0.231615    0.0800317   -0.158086    0.277921      -0.129316   -0.104571  
 -0.149294   -0.0130248    0.186275   -0.219746       0.0673901   0.0798606 
 -0.131878   -0.00396265   0.169037   -0.204038   …   0.0539454   0.0662375 
 -0.14514    -0.0332988    0.168384   -0.190066       0.0778299   0.0867255 
 -0.0299641   0.0372326    0.0617453  -0.0918129     -0.0120473  -0.00309877
 -0.205216   -0.0839698    0.137149   -0.232933       0.0895106   0.0971193 
 -0.100475   -0.114933    -0.088079   -0.0435633      0.046928   -0.0048387 
 -0.133733   -0.109897    -0.0247458  -0.0985453  …   0.0587572   0.0114353 
 -0.128643   

Heritability estimate from 13-variate analysis.

In [54]:
h, hse = heritability(alltrait_model.Σ, Σcov)
[h'; hse']

2x13 Array{Float64,2}:
 0.274338  0.219669   0.329511   0.279019   …  0.172946  0.117315   0.10642  
 0.07785   0.0818365  0.0727477  0.0775928     0.087259  0.0902116  0.0903971

## Save analysis results

In [16]:
#@save "copd.jld"
whos()

                 #130#wsession    280 bytes  JLD.JldWriteSession
                 #132#wsession    280 bytes  JLD.JldWriteSession
                 #159#wsession    280 bytes  JLD.JldWriteSession
                    ArrayViews    184 KB     Module
                          Base  34997 KB     Module
                       BinDeps    208 KB     Module
                         Blink    102 KB     Module
                         Blosc     37 KB     Module
                        Codecs     25 KB     Module
                    ColorTypes    323 KB     Module
                        Colors    764 KB     Module
                        Compat    315 KB     Module
                         Conda     65 KB     Module
                          Core   6865 KB     Module
                    DataArrays    784 KB     Module
                    DataFrames   1837 KB     Module
                        Docile    414 KB     Module
                        FileIO    538 KB     Module
             FixedPointNu